name: Integration tests
on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/gfmodules-trigger-ci@gfmodules-trigger-ci
        with:
          orac_htpassword: ${{ secrets.ORAC_HTPASSWD }}
          endpoint_url: https://orac.test.gf.irealisatie.nl/run
